### ISSUE TITLE
Sending "more hot water" command

### ISSUE THREAD

**Issue by db-EV** [pajzo/myuplink#6]
Hej!

First of all: Thanks for your work with the integration of myUplink to Home Assistant!
Works fine to get values from the different data points.

But I have a feature request ;-)
It would be nice to have a button/switch to send the "more hot water" command to the heatpump.

**Comment by astrandb** [comment]
Thank you for your comment.
There are a lot of features in the pipeline and we hope that switches for boost hot water and forced ventilation will be ready for the march release of Home assistant.

**Comment by db-EV** [comment]
Thanks for your answer!

> PS This repo is only for the library that interfaces the myUplink cloud with Home Assistant. This type of issue should be entered in Home Assistant Core repo.
Ok, I will do so in the future.
