### ISSUE TITLE
Adding sensors for the energy dashboard

### ISSUE THREAD

**Issue by db-EV** [pajzo/myuplink#7]
Right now the sensors for produced and used energy can't be used in the energy dashboard.
I started with a helper sensor but I didn't managed yet to get it work for the energy dashboard, otherwise it seems to calculate correctly.

Even a sensor for COP would be nice, just some suggestion for the future development ;-)

**Comment by astrandb** [comment]
We plan to fix this in upcoming release of HA - 2024.3.0

Note: This type of issue/request should be adressed to Home Assistant Core repo

**Comment by db-EV** [comment]
Thanks for your answer!

> Note: This type of issue/request should be adressed to Home Assistant Core repo

Ok, I will do so in the future.
